CREATE TABLE IF NOT EXISTS public.online_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  paypal_order_id TEXT NOT NULL UNIQUE,
  paypal_capture_id TEXT UNIQUE,
  order_reference TEXT NOT NULL UNIQUE,
  customer_name TEXT NOT NULL,
  customer_email TEXT NOT NULL,
  phone TEXT,
  party INTEGER NOT NULL CHECK (party BETWEEN 1 AND 12),
  requested_date DATE NOT NULL,
  requested_time TIME NOT NULL,
  notes TEXT,
  fulfillment TEXT NOT NULL CHECK (fulfillment IN ('reservation', 'delivery')),
  delivery_commune TEXT,
  delivery_address TEXT,
  items JSONB NOT NULL,
  subtotal_usd NUMERIC(10, 2) NOT NULL CHECK (subtotal_usd >= 0),
  delivery_fee_usd NUMERIC(10, 2) NOT NULL DEFAULT 0 CHECK (delivery_fee_usd >= 0),
  total_usd NUMERIC(10, 2) NOT NULL CHECK (total_usd > 0),
  payment_status TEXT NOT NULL DEFAULT 'pending' CHECK (payment_status IN ('pending', 'paid', 'refunded')),
  paid_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT online_orders_delivery_details CHECK (
    (fulfillment = 'delivery' AND delivery_commune IS NOT NULL AND delivery_address IS NOT NULL AND delivery_fee_usd = 15)
    OR (fulfillment = 'reservation' AND delivery_commune IS NULL AND delivery_address IS NULL AND delivery_fee_usd = 0)
  )
);

CREATE INDEX IF NOT EXISTS online_orders_status_created_idx
  ON public.online_orders (payment_status, created_at DESC);

CREATE INDEX IF NOT EXISTS online_orders_fulfillment_date_idx
  ON public.online_orders (fulfillment, requested_date, requested_time);

ALTER TABLE public.online_orders ENABLE ROW LEVEL SECURITY;